// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB4HSPV1SzThYm0IBmmE-QyVdkl5fCfOY',
    appId: '1:136031066852:web:0823c152e4aa37d41eaaf1',
    messagingSenderId: '136031066852',
    projectId: 'e-learning-23dc0',
    authDomain: 'e-learning-23dc0.firebaseapp.com',
    storageBucket: 'e-learning-23dc0.appspot.com',
    measurementId: 'G-P7DWHBQT9R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGPsZZqhvFHuQrX_4Do_Rs156e6fw6Vus',
    appId: '1:136031066852:android:a6ea2476f99234641eaaf1',
    messagingSenderId: '136031066852',
    projectId: 'e-learning-23dc0',
    storageBucket: 'e-learning-23dc0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDe6NvLmaBjxpVx20tjJdxmWjEYQX3nX24',
    appId: '1:136031066852:ios:2f6c09670b3a6f001eaaf1',
    messagingSenderId: '136031066852',
    projectId: 'e-learning-23dc0',
    storageBucket: 'e-learning-23dc0.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDe6NvLmaBjxpVx20tjJdxmWjEYQX3nX24',
    appId: '1:136031066852:ios:2f6c09670b3a6f001eaaf1',
    messagingSenderId: '136031066852',
    projectId: 'e-learning-23dc0',
    storageBucket: 'e-learning-23dc0.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCB4HSPV1SzThYm0IBmmE-QyVdkl5fCfOY',
    appId: '1:136031066852:web:e7a21822ef9bc1ae1eaaf1',
    messagingSenderId: '136031066852',
    projectId: 'e-learning-23dc0',
    authDomain: 'e-learning-23dc0.firebaseapp.com',
    storageBucket: 'e-learning-23dc0.appspot.com',
    measurementId: 'G-9LW77TWWMV',
  );
}
